# Get passed arguments
METHOD="$1";
ARGS=("$@");

# Set vars
HR===============================================;

# Set text colours
GREEN=`tput setaf 2`
RED=`tput setaf 1`
RESET=`tput sgr0`

# Set complete strings
UPLOAD="${GREEN}✔ UPLOAD COMPLETE ${RESET}"
REBASE="${GREEN}✔ REBASE COMPLETE ${RESET}"
IMPORTREMOTE="${GREEN}✔ DATABASE IMPORTED TO REMOTE ${RESET}"
IMPORTLOCAL="${GREEN}✔ DATABASE IMPORTED TO LOCAL ${RESET}"
EXPORTREMOTE="${GREEN}✔ REMOTE DATABASE EXPORTED ${RESET}"
EXPORTLOCAL="${GREEN}✔ LOCAL DATABASE EXPORTED ${RESET}"
DBCONF="${GREEN}✔ DATABASE CONFIG FILES CREATED ${RESET}"
